FROM freqtradeorg/freqtrade:stable

USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    ca-certificates \
 && wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
 && tar -xzf ta-lib-0.4.0-src.tar.gz \
 && cd ta-lib \
 && ./configure --prefix=/usr \
 && make \
 && make install \
 && ldconfig \
 && cd / \
 && rm -rf ta-lib ta-lib-0.4.0-src.tar.gz /var/lib/apt/lists/*

USER ftuser

