services:
  freqtrade:
    image: freqtradeorg/freqtrade:2025.12
    container_name: freqtrade_upbit
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data
      #- ./upbit_exchange_stable/ohlcv:/data/ohlcv:ro
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy UpbitMicroStructureStrategy

