# constants.py
# 공통 상수 및 기본값

UPBIT_WS_URL = "wss://api.upbit.com/websocket/v1"

# 기본 페어 설정
DEFAULT_PAIRS = ["KRW-BTC", "KRW-ETH", "KRW-XRP"]

# 기본 운영 설정
DEFAULT_MAX_LATE_MS = 2000
DEFAULT_STATS_INTERVAL = 30.0
DEFAULT_HTTP_PORT = 0

# 큐 설정
DEFAULT_QUEUE_HIGH_WATERMARK = 8000
DEFAULT_QUEUE_HARD_LIMIT = 10000
DEFAULT_WRITER_QUEUE_HIGH_WATERMARK = 8000
DEFAULT_WRITER_QUEUE_HARD_LIMIT = 10000

# DB 설정
DEFAULT_BATCH_SIZE = 100
DEFAULT_DERIVED_MAX_STORE = 1000

# 재연결 정책 (DEC-009, DEC-010)
RECONNECT_BASE_DELAY = 1.0
RECONNECT_MAX_DELAY = 60.0
RECONNECT_JITTER_MAX = 1.0
RECONNECT_WINDOW_SECONDS = 600.0
RECONNECT_WINDOW_MAX_ATTEMPTS = 10
RECONNECT_COOLDOWN_SECONDS = 300.0
PERIODIC_RECONNECT_SECONDS = 9 * 60 * 60  # 9시간

# 전역 레이트리밋
GLOBAL_RECONNECT_PER_SECOND = 1
GLOBAL_RECONNECT_PER_MINUTE = 30
